force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/Job_Application_Task__c.object-meta.xml
<CustomObject>
    <description>Custom sObject containing the &apos;metadata&apos; for the Tasks assigned at different Job Application Statuses.</description>
    <label>Job Application Task</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Application Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application_Task__c/fields/Due_Date_Adjust__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_Adjust__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Used to adjust the Due Date (ActivityDate) of a Task.</description>
    <label>Due Date Adjust</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/fields/Job_Appl_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Appl_Status__c</fullName>
    <label>Job Appl Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Job_Application_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/fields/Task_Comment__c.field-meta.xml
<CustomField>
    <fullName>Task_Comment__c</fullName>
    <inlineHelpText>Will appear in Task Comment field (API name &apos;Description&apos;.</inlineHelpText>
    <label>Task Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/fields/Task_Priority__c.field-meta.xml
<CustomField>
    <fullName>Task_Priority__c</fullName>
    <label>Task Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/fields/Task_Subject__c.field-meta.xml
<CustomField>
    <fullName>Task_Subject__c</fullName>
    <inlineHelpText>Will appear in Task Subject field</inlineHelpText>
    <label>Task Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Job_Application_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Saved</fullName>
    </customValue>
    <customValue>
        <fullName>Applying</fullName>
    </customValue>
    <customValue>
        <fullName>Applied</fullName>
    </customValue>
    <customValue>
        <fullName>Interviewing</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiating</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Job Application Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/JobApplicationHelper.cls
public with sharing class JobApplicationHelper {
    
    // Method to create/insert Tasks, if any, when a Job Application record is created/inserted.
    public static void createJobAppTasksAfterInsert(List<Job_Application__c> listJobAppl) {
        
        // Get the Task templates from the Org Cache
        List<Job_Application_Task__c> listJobAppTasks = Utilities.getJobAppTasks();         
        // Initialize a List<Tasks> to store the Tasks that will be created.
        List<Task> listTasksToCreate = new List<Task>();
        
        // Loop thru the List of Job Appl. (Trigger.new)
        for (Job_Application__c jobAppl : listJobAppl) {
            
            // Loop thru the Task templates
            for (Job_Application_Task__c jobApplTask : listJobAppTasks) {
                
                System.debug('***********' + JSON.serializePretty(jobApplTask));
                
                // // If the the Job Application Status = template Status then create a new Task from the template
                // if (jobAppl.Status__c == jobApplTask.Job_Appl_Status__c) {
                    
                //     Task tsk = new Task();
                //     tsk.OwnerId = UserInfo.getUserId();
                //     //tsk.WhoId = 
                //     tsk.WhatId = jobAppl.Id;
                //     tsk.Subject = jobApplTask?.Task_Subject__c;
                //     tsk.Description = jobApplTask?.Task_Comment__c;
                //     tsk.Priority = jobApplTask?.Task_Priority__c;
                    
                //     System.debug('jobApplTask.Due_Date_Adjust__c: ' + String.valueOf(jobApplTask.Due_Date_Adjust__c));
                    
                //     //if (jobApplTask.Due_Date_Adjust__c != 0) {
                //         tsk.ActivityDate = Utilities.addWorkingDays(Date.today(), 5);
                //     //} else {
                //     //
                //     listTasksToCreate.add(tsk);
            }
            
        } 
        
        insert listTasksToCreate;

        return;
    }

    
    // public static List<Task> createJobAppTasksBeforeUpdate(List<Job_Application__c> listJobApplOld, List<Job_Application__c> listJobApplNew) {
        
    //     return null;
    // }

}