force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <description>The Account record representing the company/entity with the job opening.</description>
    <inlineHelpText>Account record that is the Employer for this job.</inlineHelpText>
    <label>Employer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employer</value>
        </filterItems>
        <infoMessage>Available options are Accounts of Employer RecordType.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/JoobleId__c.field-meta.xml
<CustomField>
    <fullName>JoobleId__c</fullName>
    <externalId>true</externalId>
    <label>JoobleId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Employer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Job_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/Job_Application_Task__c.object-meta.xml
<CustomObject>
    <description>Custom sObject containing the &apos;metadata&apos; for the Tasks assigned at different Job Application Statuses.</description>
    <label>Job Application Task</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Application Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application_Task__c/fields/Job_Appl_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Appl_Status__c</fullName>
    <label>Job Appl Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Job_Application_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/fields/Task_Comment__c.field-meta.xml
<CustomField>
    <fullName>Task_Comment__c</fullName>
    <inlineHelpText>Will appear in Task Comment field (API name &apos;Description&apos;.</inlineHelpText>
    <label>Task Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/fields/Task_Priority__c.field-meta.xml
<CustomField>
    <fullName>Task_Priority__c</fullName>
    <label>Task Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/fields/Task_Subject__c.field-meta.xml
<CustomField>
    <fullName>Task_Subject__c</fullName>
    <inlineHelpText>Will appear in Task Subject field</inlineHelpText>
    <label>Task Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Job_Application_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Saved</fullName>
    </customValue>
    <customValue>
        <fullName>Applying</fullName>
    </customValue>
    <customValue>
        <fullName>Applied</fullName>
    </customValue>
    <customValue>
        <fullName>Interviewing</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiating</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Job Application Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Job_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Job Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/JobApplicationHelperUpdateTest.cls
@IsTest
private class JobApplicationHelperUpdateTest {
    
    @TestSetup
    static void setupData() {
                      
        List<Account> accList = new List<Account>();
        Account accs = new Account(Name = 'testEmployer');
        accList.add(accs);
       
        TriggerHandler.bypass('AccountTriggerHandler');
        insert accList;      
        TriggerHandler.clearBypass('AccountTriggerHandler');

        accs = [SELECT Id FROM Account LIMIT 1];
        Contact cont = new Contact(LastName = '<unknown_contact>', AccountId = accs.Id);
        insert cont;
    
        Account acc = [SELECT Id FROM Account];
        Contact con = [SELECT Id FROM Contact];
    
        Job__c job = new Job__c();
        job.Employer__c = acc.Id;
        job.Primary_Contact__c = con.Id;
        job.JoobleId__c = '12345';
        insert job;

        List<Job_Application_Task__c> jaTasks = new List<Job_Application_Task__c>();
        Job_Application_Task__c jaTask = new Job_Application_Task__c();
        jaTask.Active__c = true;
        jaTask.Job_Appl_Status__c = 'Saved';
        jaTask.Task_Subject__c = 'Task1';
        jaTask.Task_Comment__c = 'Task1';
        jaTask.Task_Priority__c = 'High';
        jaTasks.add(jaTask);
        Job_Application_Task__c jaTask2 = new Job_Application_Task__c();
        jaTask2.Active__c = true;
        jaTask2.Job_Appl_Status__c = 'Applying';
        jaTask2.Task_Subject__c = 'Task2';
        jaTask2.Task_Comment__c = 'Task2';
        jaTask2.Task_Priority__c = 'High';
        jaTasks.add(jaTask2);  
        insert jaTasks;

        System.debug(JSON.serializePretty(jaTasks)); 
         
        Job_Application__c jobApp = new Job_Application__c();
        jobApp.Job__c = job.Id;
        insert jobApp;

    }
    
    @IsTest
    static void testProcessJobAppTasksAfterUpdate() {

        Test.startTest();   
       
        Job_Application__c ja = [SELECT Id, Status__c FROM Job_Application__c];
                
        List<Task> tasks = [SELECT Id FROM Task WHERE WhatId = :ja.Id];
        System.debug('Before update: ' + JSON.serializePretty(tasks));
        Integer createSize = tasks.size();
        
        System.debug('ja before update: ' + JSON.serializePretty(ja));
        ja.Status__c = 'Applying';
        System.debug('ja after change: ' + JSON.serializePretty(ja));
        
        update ja;  
        
        Test.stopTest();

        System.debug('ja before update: ' + JSON.serializePretty(ja));
        tasks = [SELECT Id FROM Task WHERE WhatId = :ja.Id];
        System.debug('After update: ' + JSON.serializePretty(tasks));
        
        System.assertNotEquals(createSize, tasks.size());

    }
    
    

    
}