force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <description>The Account record representing the company/entity with the job opening.</description>
    <inlineHelpText>Account record that is the Employer for this job.</inlineHelpText>
    <label>Employer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employer</value>
        </filterItems>
        <infoMessage>Available options are Accounts of Employer RecordType.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/IsCreated__c.field-meta.xml
<CustomField>
    <fullName>IsCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to conditionally hide/show form and layout fields.</description>
    <label>IsCreated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Long_Name__c.field-meta.xml
<CustomField>
    <fullName>Long_Name__c</fullName>
    <description>Used to hold the concatenated Position (Name) and Employer Name values.</description>
    <inlineHelpText>A concatenation of the Job Name (Position) and Employer fields.</inlineHelpText>
    <label>Position (Long)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobTriggerHandler.cls
public class JobTriggerHandler extends TriggerHandler {
    
    private List<Job__c> jobTriggerNew;
    private List<Job__c> jobTriggerOld;
    private Map<Id,Job__c> jobTriggerNewMap;
    private Map<Id,Job__c> jobTriggerOldMap;

    public JobTriggerHandler() {
        this.jobTriggerNew = (List<Job__c>) Trigger.new;
        this.jobTriggerOld = (List<Job__c>) Trigger.old;
        this.jobTriggerNewMap = (Map<Id, Job__c>) Trigger.newMap;
        this.jobTriggerOldMap = (Map<Id, Job__c>) Trigger.oldMap;
    }
 
    public override void beforeInsert() {
        
        // Execute a query to retrieve Relationship fields, which are not in triggers
        List<Job__c> jobsToUpdateList = [SELECT Id, IsCreated__c, Name, Employer__r.Name, Long_Name__c FROM Job__c WHERE Id IN :Trigger.new WITH SYSTEM_MODE];
        Map<Id,Job__c> jobsToUpdateMap = new Map<Id,Job__c>(jobsToUpdateList);
        // Loop thru the List and update the IsCreated__c field
        for (Job__c job : (List<Job__c>) Trigger.new) {
            job.IsCreated__c = true;
            Job__c jobFromMap = (Job__c) jobsToUpdateMap.get(Job.Id);
            System.debug('jobFromMap:' + JSON.serializePretty(jobFromMap));
            //job.Long_Name__c = job.Name + ' (' + jobFromMap.Employer__r.Name + ')';
        }
        
    }

    public override void afterInsert() {
    }

    public override void beforeUpdate() {
       
        // Update Long_Name__c if the Position (API Name) field changes.
        for (Job__c newJob : (List<Job__c>) Trigger.new ) {
            Job__c oldJob = (Job__c) Trigger.oldMap?.get(newJob.Id);
            if (newJob.Name != oldJob.Name) {
                String revLongName = newJob.Long_Name__c.replace(oldJob.Name, newJob.Name);
                newJob.Long_Name__c = revLongName;
            }
        }

    }

    public override void afterUpdate() {
    }

    public override void beforeDelete() {
    }

    public override void afterDelete() {
    }

    public override void afterUndelete() {     
    }
}