force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <description>The Account record representing the company/entity with the job opening.</description>
    <inlineHelpText>Account record that is the Employer for this job.</inlineHelpText>
    <label>Employer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employer</value>
        </filterItems>
        <infoMessage>Available options are Accounts of Employer RecordType.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobHelperTest.cls
@IsTest
private class JobHelperTest {
    
    @TestSetup
    static void setupData(){
        
        List<Account> accList = new List<Account>();
        Account acc = new Account(Name = 'testEmployer');
        accList.add(acc);
        
        TriggerHandler.bypass('AccountTriggerHandler');
        insert accList;      
        TriggerHandler.clearBypass('AccountTriggerHandler');
        
        Contact cont = new Contact(LastName = '<unknown_contact>', AccountId = accList[0].Id);
        insert cont;

    }
    
    
    
    @IsTest
    static void getJoobleResponseFromMock() {

        Map<String, String> JoobleKeywordsMap = new Map<String,String>{
            'keywords' => 'Salesforce developer',
            'location' => 'Des Moines, Iowa',
            'salary' => '70000',
            'datecreatedfrom' => '2023-01-01',
            'companysearch' => 'false'
        };
        
        Test.setMock(HttpCalloutMock.class, new JoobleJSONCalloutMockGenerator());

        Test.startTest();
        JobHelper.JoobleCallout(JSON.serialize(JoobleKeywordsMap));
        Test.stopTest();

        Account acc = [SELECT Id, Name FROM Account WHERE Name != 'testEmployer'];
        System.assertEquals('Principal Financial Group', acc.Name);
        Job__c job = [SELECT Id, Name, Employer__r.Name FROM Job__c];
        System.assertEquals('Principal Financial Group', job.Employer__r.Name);
        System.assertEquals('TESTSalesforce Developer (Hybrid)', job.Name);

    } 

}