force-app/main/default/objects/Account/recordTypes/Employer.recordType-meta.xml
<RecordType>
    <fullName>Employer</fullName>
    <active>true</active>
    <description>Represents the Employer for a Job Application</description>
    <label>Employer</label>
</RecordType>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <description>The Account record representing the company/entity with the job opening.</description>
    <inlineHelpText>Account record that is the Employer for this job.</inlineHelpText>
    <label>Employer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employer</value>
        </filterItems>
        <infoMessage>Available options are Accounts of Employer RecordType.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/IsCreated__c.field-meta.xml
<CustomField>
    <fullName>IsCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to conditionally hide/show form and layout fields.</description>
    <label>IsCreated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Employer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/JobTriggerHandlerTest.cls
@IsTest
private class JobTriggerHandlerTest {
    
    @TestSetup
    static void setupData() {
              
        List<Account> accList = new List<Account>();
        Account acc = new Account(Name = 'testEmployer');
        accList.add(acc);
        
        TriggerHandler.bypass('AccountTriggerHandler');
        insert accList;      
        TriggerHandler.clearBypass('AccountTriggerHandler');
        
        Contact cont = new Contact(LastName = 'testPrimCont');
        insert cont;
        
    }
      
    @IsTest 
    static void testJobTriggerHandlerInsert() {
        
        Job__c job = new Job__c();
        job.Name = 'testJob';
        
        Account employer = [SELECT Id FROM Account LIMIT 1];
        job.Employer__c = employer.Id;

        Contact cont = [SELECT Id FROM Contact LIMIT 1];
        job.Primary_Contact__c = cont.Id;
                
        Test.startTest();
        insert job;
        System.assertEquals(true, job.IsCreated__c);
        Test.stopTest();    

    }

}