force-app/main/default/objects/Job_Application_Task__c/Job_Application_Task__c.object-meta.xml
<CustomObject>
    <description>Custom sObject containing the &apos;metadata&apos; for the Tasks assigned at different Job Application Statuses.</description>
    <label>Job Application Task</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Application Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application_Task__c/fields/Job_Appl_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Appl_Status__c</fullName>
    <label>Job Appl Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Job_Application_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/fields/Task_Comment__c.field-meta.xml
<CustomField>
    <fullName>Task_Comment__c</fullName>
    <inlineHelpText>Will appear in Task Comment field (API name &apos;Description&apos;.</inlineHelpText>
    <label>Task Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/fields/Task_Priority__c.field-meta.xml
<CustomField>
    <fullName>Task_Priority__c</fullName>
    <label>Task Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application_Task__c/fields/Task_Subject__c.field-meta.xml
<CustomField>
    <fullName>Task_Subject__c</fullName>
    <inlineHelpText>Will appear in Task Subject field</inlineHelpText>
    <label>Task Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Job_Application_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Saved</fullName>
    </customValue>
    <customValue>
        <fullName>Applying</fullName>
    </customValue>
    <customValue>
        <fullName>Applied</fullName>
    </customValue>
    <customValue>
        <fullName>Interviewing</fullName>
    </customValue>
    <customValue>
        <fullName>Negotiating</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Job Application Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/JobApplicationTaskTriggerHandlerTest.cls
@IsTest
private class JobApplicationTaskTriggerHandlerTest {
    
    static void testGetJpbAppTasks() {

        List<Job_Application_Task__c> jaTasks = new List<Job_Application_Task__c>();
        Job_Application_Task__c jaTask = new Job_Application_Task__c();
        jaTask.Active__c = true;
        jaTask.Job_Appl_Status__c = 'Saved';
        jaTask.Task_Subject__c = 'Task1';
        jaTask.Task_Comment__c = 'Task1';
        jaTask.Task_Priority__c = 'High';
        jaTasks.add(jaTask);

        insert jaTask;
        List<Job_Application_Task__c> jaTaskFromCache = [SELECT Id, Task_Comment__c FROM Job_Application_Task__c];
        System.assertEquals(1, jaTaskFromCache.size());

        jaTaskFromCache[0].Task_Comment__c = 'updated';
        update jaTaskFromCache;
        jaTaskFromCache = Utilities.getJobAppTasks();
        System.assert(jaTaskFromCache[0].Task_Comment__c == 'updated');

        delete jaTaskFromCache;
        jaTaskFromCache = Utilities.getJobAppTasks();
        System.assert(jaTaskFromCache.size() == 0);

    }
}